### ISSUE TITLE
Make `toSatisfyApiSpec` more specific

### ISSUE THREAD

**Issue by karlismelderis** [openapi-library/OpenAPIValidators#213]
**OpenAPI version**
2 and/or 3

**Is your feature request related to a problem? Please describe.**
if toSatisfyApiSpec is used alone test case feels bit to loose and hard to reason about in PR review.

```js
  it('should satisfy OpenAPI spec', async () => {
    // Get an HTTP response from your server (e.g. using axios)
    const res = await axios.get('http://localhost:3000/example/endpoint');
    // Assert that the HTTP response satisfies the OpenAPI spec
    expect(res).toSatisfyApiSpec();
  });
```

Not knowing internals of matcher if feels like any response - 200, 4xx, 5xx that's described in API spec will pass the test.

errors/typos happen.
People sometimes write tests with single `expect`.
So single expect statement might be more self-explanatory if taken out of context.

**Describe the solution you'd like**
can we try like this:
```js
  it('should satisfy OpenAPI spec', async () => {
    // Get an HTTP response from your server (e.g. using axios)
    const res = await axios.get('http://localhost:3000/example/');
    // Assert that the HTTP response satisfies the OpenAPI spec
    expect(res).toSatisfyApiSpec({
      path: '/collection/:id'
      statusCode: '404'
      httpMethod: 'post'
    });
  });
```

if I'm reviewing such test case it's already visible that something is wrong

**Describe alternatives you've considered**
Adding extra `expect` statements helps but they are not always added.

**Are you going to resolve the issue?**
I guess I'm looking for consensus here first 😉

**Comment by rwalle61** [comment]
Thanks for your suggestion @karlismelderis!

I agree `toSatisfyApiSpec` on it's own doesn't make clear which definition your response object satisfies. However are we sure extending `toSatisfyApiSpec` as you suggest is better than "Adding extra `expect` statements"?

> but they [expect statements] are not always added.

Well, we could just insist that people add them. Okay, but isn't this assertion better:
```js
expect(res).toSatisfyApiSpec({
      path: '/collection/:id'
      statusCode: '404'
      httpMethod: 'post'
    });
```

But is it really easier to read, write, and debug than this?
```js
expect(res.path).toEqual('/collection/:id');
expect(res.statusCode).toEqual(404);
expect(res.method).toEqual('post');
//...
```

Some will prefer the first, others the second. At least we can agree the benefit not big.

The cost is that `toSatisfyApiSpec` is more complex to use (and for us to maintain).

That said, I'm open to discussion - let me know what you think, I may have missed some large benefits of this :)

**Comment by doc-balto** [comment]
I had a similar thought. We're using this tool for both contract validation and integration test response validation, but wanted to be explicit as to _which_ response body it validated against. 

I ended up writing a Chai method that wrapped a check for a status code, which made our tests super readable. Here's what I ended up doing:

```
	Assertion.addMethod("satisfyApiSpecResponse", function(expectedStatusCode) {
		return this._obj.then(response => {
			response.should.satisfyApiSpec;
			if (expectedStatusCode) {
				this.assert(
					response.status === expectedStatusCode,
					"expected response status code to be #{exp} but got #{act}",
					"expected response status code to not be #{act}",
					expectedStatusCode,
					response.status
				);
			}
		}).catch((e) => {
			console.log(e);
			throw e;
		});
	});
	```
	
And then my test looks like:

```
			return axios.post(url, body)
				.should.eventually.satisfyApiSpecResponse(200);
```

And gives me some reasonable expectation that it validated against a specific response, (as opposed to one of the other successful responses defined).

Admittedly, we just started this pattern, and have already found cases where we have to explicitly validate on particular properties of the response, so I can understand the hesitation. Just thought I'd share some of how we're using the tool.

**Comment by karlismelderis** [comment]
Agree.
Maybe status code would be enough to narrow down what response is expected to happen.

HTTP method and path can be assumed/predicted from request where status code can flip between 200/500 and test would still pass.

**Comment by rwalle61** [comment]
Thanks @karlismelderis and @doc-balto for your discussion :) 

Yea I agree: 
>Maybe status code would be enough to narrow down what response is expected to happen.

It sounds like existing behaviour is enough, especially if users assert on the status. That's what we have in our [existing examples](https://github.com/openapi-library/OpenAPIValidators/tree/master/packages/jest-openapi#1-write-a-test). But if it could be clearer, please suggest how / raise a PR clarifying it. This discussion also clarifies things for users, so thanks. 

Further, users can even extend the chai/jest plugin as @doc-balto suggested.

I'll close this then. If more users want this functionality in future, feel free to reopen!
