### ISSUE TITLE
Array path params

### ISSUE THREAD

**Issue by amitkeinan9** [openapi-library/OpenAPIValidators#250]
**Which package are you using**?
`jest-openapi`

**OpenAPI version**
3

**Describe the bug**
When testing a route that accepts an array as a path parameter for example: `/groups/{ids}` where ids is a comma separated array (`/groups/1,2`) the test fails with an error the the requested path is not in the API spec while printing the available paths including `groups{ids}`. 

I tried setting the ids parameter to be array[string] or string and both failed. 
when requesting the same path without a comma (just one id) it’s working as expected. 

**To Reproduce**

1. Create a simple yaml with array path parameter
2. Create a basic server with the path
3. Create a basic test
4. Run test 

**Expected behavior**
The test should be able to run and find the path. 

**Screenshots**
I’m sorry but I can’t really add screenshots or snippets

**Are you going to resolve the issue?**

**Comment by amitkeinan9** [comment]
Bug before fix:
![image](https://user-images.githubusercontent.com/16577335/136696665-ad24a8a2-4bee-4fc0-8fe2-03b19c6bf6ea.png)

Bug after fix:
![image](https://user-images.githubusercontent.com/16577335/136696704-69c5bf58-8852-44cb-8dab-8f317a9b0cbc.png)

Removing all commas from string solved the problem in the `style: simple explode: false` case

**Comment by amitkeinan9** [comment]
Opened a PR

**Comment by rwalle61** [comment]
Thanks! Will take a look

**Comment by rwalle61** [comment]
Code merged to master, will release soon. I'll close this after releasing and you've confirmed it's working 🙂

**Comment by amitkeinan9** [comment]
Works!
