### ISSUE TITLE
Support for $refs inside schemas

### ISSUE THREAD

**Issue by Nitwel** [openapi-library/OpenAPIValidators#90]
Using openapi v3.0.1
I run into the issue that when I use $refs inside schemas, I get the error: `should NOT have additional properties`.
It would be nice if this would be supported or at least dont throw an error.
But if you want to implement this you have to concider, that they could not always be provided from the server so it should check it the nested schmea exists in the response and if so, validate it.

Also thank you for this tool. 👍

**Comment by rwalle61** [comment]
Thanks for this as well @Nitwel. Do you have a specific example or test case to recreate this?

**Comment by Nitwel** [comment]
Have a look at the project I'm currently working on: 
https://github.com/directus/SDK-Generator/blob/e2c9a90f90b9df3b63e9628ddd3e93757e0ae6a9/specs/components/file.yaml#L79

My solution at the moment is that I merge all files into one big json file and remove all $ref's with openapi-cli.

**Comment by tgiardina** [comment]
Hi @Nitwel,

The link you provided is now dead. Is this still a problem for you? If it is, consider forking this repo, recreating the bug in the [bugRecreationTemplate](https://github.com/openapi-library/OpenAPIValidators/blob/master/commonTestResources/exampleOpenApiFiles/valid/bugRecreationTemplate/openapi.yml), and then linking to your forked repo here.

**Comment by rwalle61** [comment]
I'm closing this issue as it seems stale, but people can reopen if they need the enhancement
